"""Entity domain constants (4×4 magic square)."""

GRID_SIZE = 4

BLANK_CELL_VALUE = 0
REQUIRED_BLANK_COUNT = 2
CELL_VALUE_MIN = 1
CELL_VALUE_MAX = GRID_SIZE * GRID_SIZE

MAGIC_SUM = GRID_SIZE * (GRID_SIZE * GRID_SIZE + 1) // 2

SOLUTION_VECTOR_LENGTH = 6
