"""Boundary failure contract constants (PRD §8.1 INVALID_SIZE)."""

from src.control.constants import (
    BLANK_CELL_VALUE,
    CELL_VALUE_MAX,
    CELL_VALUE_MIN,
    GRID_SIZE,
    REQUIRED_BLANK_COUNT,
    SOLUTION_VECTOR_LENGTH,
)

GRID_SIZE_LABEL = f"{GRID_SIZE}x{GRID_SIZE}"
CELL_VALUE_RANGE_LABEL = f"{CELL_VALUE_MIN}~{CELL_VALUE_MAX}"

INVALID_SIZE_CODE = "INVALID_SIZE"
INVALID_SIZE_MESSAGE = f"Grid must be {GRID_SIZE_LABEL}."

EMPTY_COUNT_CODE = "E002"
EMPTY_COUNT_MESSAGE = "빈칸(0)은 정확히 2개여야 합니다."

CELL_RANGE_CODE = "E004"
CELL_RANGE_MESSAGE = (
    f"셀 값은 {BLANK_CELL_VALUE} 또는 {CELL_VALUE_RANGE_LABEL}이어야 합니다."
)

DUPLICATE_CODE = "E005"
DUPLICATE_MESSAGE = "0을 제외한 값은 중복될 수 없습니다."

NO_SOLUTION_CODE = "E_NO_SOLUTION"
NO_SOLUTION_MESSAGE = "두 빈칸을 채워도 마방진이 되지 않습니다."
