"""Boundary failure contract constants (PRD §8.1 INVALID_SIZE)."""

GRID_SIZE = 4

INVALID_SIZE_CODE = "INVALID_SIZE"
INVALID_SIZE_MESSAGE = "Grid must be 4x4."

BLANK_CELL_VALUE = 0
REQUIRED_BLANK_COUNT = 2

CELL_VALUE_MIN = 1
CELL_VALUE_MAX = GRID_SIZE * GRID_SIZE

EMPTY_COUNT_CODE = "E002"
EMPTY_COUNT_MESSAGE = "빈칸(0)은 정확히 2개여야 합니다."

CELL_RANGE_CODE = "E004"
CELL_RANGE_MESSAGE = "셀 값은 0 또는 1~16이어야 합니다."
