"""Boundary failure contract constants (PRD §8.1 INVALID_SIZE)."""

GRID_SIZE = 4

INVALID_SIZE_CODE = "INVALID_SIZE"
INVALID_SIZE_MESSAGE = "Grid must be 4x4."

BLANK_CELL_VALUE = 0
REQUIRED_BLANK_COUNT = 2

EMPTY_COUNT_CODE = "E002"
EMPTY_COUNT_MESSAGE = "빈칸(0)은 정확히 2개여야 합니다."
